name: awesome_image_selector
description: A package to help you select, view, and edit an image with an easy workflow.
version: 0.0.2
homepage: https://salehwaleed.com

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  image_picker_web: ^3.1.1
  web_image_picker: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2


flutter:


